id: P0D4D7134
initial_creation_type: input
source_metadata:
  title: Lodi Gyari Rinpoche
  language: bo
  description: Texts by or related to Lodi Gyari Rinpoche, also known as Pema Lodrö
    Gyaltsen (padma blo gros rgyal mtshan, 1949–2018), who was the special envoy to
    His Holiness the Dalai Lama in Washington DC.
  volume:
    1ecd9bd8d30a48049c9fbbac5894674a:
      title: Prayer to His Holiness the Dalai Lama
      parent: Prayers
    40dfb930fc6a45cdbc52428ce02cd4c2:
      title: Long Life Prayer for Lodi Gyari Rinpoche
      parent: Long Life Prayers
    1a223b174dcf4666adbfe56a194a2c0c:
      title: A Plaintive Prayer to Guru Rinpoche
      parent: Guru Rinpoche Prayers
    9afba73535cf4b5484ff56497bf514cb:
      title: Offering Prayer to Changshönma, Protectress Riding upon a Wolf
      parent: Dharma Protectors
created_at: '2022-03-01T00:39:16.900628'
last_modified_at: '2022-03-01T00:39:16.900630'
